<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TeamsAITeammate.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Graph" Version="*-*" />
    <PackageReference Include="Azure.Search.Documents" Version="*-*" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="*-*" />
    <PackageReference Include="Newtonsoft.Json" Version="*" />
    <PackageReference Include="Azure.Identity" Version="*-*" />
    <PackageReference Include="Azure.Storage.Blobs" Version="*-*" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.*-*" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.*-*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TeamsAITeammate.Core\TeamsAITeammate.Core.csproj" />
  </ItemGroup>

</Project>
